### ISSUE TITLE
Access to Fetch has been blocked by CORS policy.

### ISSUE THREAD

**Issue by jmatlovsky** [ray-lee/wp-collectionspace#1]
https://fabricworkshopandmuseum.org/collection/fwm/search

The plugin has been installed, and the custom fields have been added as follows:

![image](https://user-images.githubusercontent.com/45493056/134923078-c0078923-e258-430f-99fe-9838222d696f.png)

When the page renders, there is something quite off. The sidebar looking like it is trying to come through and there is a quick flash for "No Results Found" on the right side which will disappear and re-appear as you scroll:

![image](https://user-images.githubusercontent.com/45493056/134923309-fbd75e2b-9a6e-4383-b160-5f280e234933.png)

This leads me to believe that the connection is coming through, but there is an error. I reviewed this and found the following error in the console:

![image](https://user-images.githubusercontent.com/45493056/134923501-021a0728-f99a-42f6-8700-3bfc00c7e536.png)

Since it looked like it had to do with the CORS settings in the header, I added a bit of code to the functions.php file which would allow the connection but my developer says there may be something server side we need to add to the CollectionSpace header. Here is the code that we added to the functions.php file:

`/* Allow CORS */
function add_cors_http_header() {
    header("Access-Control-Allow-Origin: *");
}
add_action('init','add_cors_http_header');`

**Comment by ray-lee** [comment]
Nothing should be required on your side, but we do need to change a server setting on fwm.collectionspace.org. Are you able to create a ZenDesk support ticket? That would be the best place to make a request for that.

**Comment by mark-cooper** [comment]
@jmatlovsky try setting the `gatewayUrl` to: https://fwm.collectionspace.org/gateway/fwm

**Comment by jmatlovsky** [comment]
That looks like it did the trick - thanks!

Best,

Jordan Matlovsky
Creative Director, Hudson Creative

79 Madison Ave, 2nd Flr
New York, NY 10016
Tel: +1 (646) 844-4952
***@***.***
hudsoncreative.com
